[project]
name = "example-usb-audio"
version = "0.0.0"
description = "USB Audio example for Tiliqua"

requires-python = "~=3.8"
dependencies = [
    "amaranth[builtin-yosys]~=0.4",
    "luna @ git+https://github.com/schnommus/luna@seb/isochronous-rebase",
]

[tool.pdm.dev-dependencies]
test = [
    "pytest",
]

[tool.pdm.scripts]
test = { cmd = "pytest" }
build_example_usb_audio = { call = "example_usb_audio.top:build()" }
build_example_mirror = { call = "example_dsp.top:build_mirror()" }
build_example_svf = { call = "example_dsp.top:build_svf()" }
build_example_vca = { call = "example_dsp.top:build_vca()" }
build_example_delay = { call = "example_dsp.top:build_delay()" }
build_example_pitch = { call = "example_dsp.top:build_pitch()" }
build_example_matrix = { call = "example_dsp.top:build_matrix()" }
build_example_diffuser = { call = "example_dsp.top:build_diffuser()" }
build_example_waveshaper = { call = "example_dsp.top:build_waveshaper()" }
