name: build & test

on: [push]

jobs:
  ubuntu-usb-audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm usb_audio
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-usb-audio.bit
          path: gateware/build/top.bit

  ubuntu-bitstream-dsp-nco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm dsp --dsp-core nco
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-dsp-svf.bit
          path: gateware/build/top.bit

  ubuntu-sim-dsp-nco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm dsp --sim --dsp-core nco
        working-directory: gateware

  ubuntu-bitstream-dsp-midicv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm dsp --dsp-core midicv
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-dsp-midicv.bit
          path: gateware/build/top.bit

  ubuntu-bitstream-xbeam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: True
            components: rustfmt, clippy, llvm-tools
            target: riscv32imac-unknown-none-elf
      - run: cargo install cargo-binutils svd2rust form
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm xbeam
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-xbeam.bit
          path: gateware/build/top.bit

  ubuntu-bitstream-selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: True
            components: rustfmt, clippy, llvm-tools
            target: riscv32imac-unknown-none-elf
      - run: cargo install cargo-binutils svd2rust form
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm selftest
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-selftest.bit
          path: gateware/build/top.bit


  ubuntu-bitstream-poly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: True
            components: rustfmt, clippy, llvm-tools
            target: riscv32imac-unknown-none-elf
      - run: cargo install cargo-binutils svd2rust form
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm polysyn
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-poly.bit
          path: gateware/build/top.bit

  ubuntu-bitstream-vectorscope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm run src/example_vectorscope/top.py
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-vectorscope.bit
          path: gateware/build/top.bit

  ubuntu-bitstream-boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: True
            components: rustfmt, clippy, llvm-tools
            target: riscv32imac-unknown-none-elf
      - run: cargo install cargo-binutils svd2rust form
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm run src/boot/top.py
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: example-boot.bit
          path: gateware/build/top.bit


  ubuntu-bitstream-boot-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm run src/boot_stub/top.py --bootaddr 0x100000
        working-directory: gateware
      - uses: actions/upload-artifact@v4
        with:
          name: bootstub1.bit
          path: gateware/build/top.bit
