name: build & test

on: [push]

jobs:
  ubuntu-example-usb-audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
      - uses: YosysHQ/setup-oss-cad-suite@v3
      - run: git submodule update --init --recursive
      - run: yosys --version
      - run: |
          pdm install
          pdm run build_tiliqua
        working-directory: gateware/example-usb-audio
      - uses: actions/upload-artifact@v3
        with:
          name: example-usb-audio.bit
          path: gateware/example-usb-audio/build/top.bit
